monotonic impl: use wrapping_sub to properly handle timer rollover
After the timer value rolls over the newer more recent value will be
negative. Calculating the duration_since with an older still positive
Instant results in a panic due to subtracting with overflow:

22:07:40.180 panicked at 'attempt to subtract with overflow',
src/monotonic_stm32f0.rs:144:20